// <auto-generated />
using System;
using ConsultaTemperatura.Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsultaTemperatura.Infra.Migrations
{
    [DbContext(typeof(ConsultaContexto))]
    partial class ConsultaContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ConsultaTemperatura.Dominio.Entidade.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TemperaturaAtual")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("TemperaturaMaxima")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("TemperaturaMinima")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("UltimaConsulta")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cidade")
                        .IsUnique();

                    b.ToTable("Consulta");
                });
#pragma warning restore 612, 618
        }
    }
}
